version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: up_espaco
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./internal/adapters/database/migrations:/migrations
    ports:
      - '5432:5432'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      APP_PORT: 8000
      DATABASE_URL: postgres://postgres:postgres@db:5432/up_espaco?sslmode=disable
    ports:
      - '8000:8000'
    command: ["/app/backend"]

volumes:
  db_data:
