ALTER TABLE students
    ADD COLUMN IF NOT EXISTS guardian_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS photo_url TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS group_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS teacher_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS birth_date DATE NULL,
    ADD COLUMN IF NOT EXISTS enrollment_code TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS blood_type TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS allergies TEXT[] NOT NULL DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS restrictions TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS medications TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS student_guardians (
    id SERIAL PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    relation TEXT NOT NULL,
    phone TEXT NOT NULL DEFAULT '',
    avatar_url TEXT NOT NULL DEFAULT '',
    authorized BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);