CREATE TABLE IF NOT EXISTS turmas (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE students ADD COLUMN IF NOT EXISTS turma_id INTEGER REFERENCES turmas(id) ON DELETE SET NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS teacher_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;
